apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-deploy
  labels:
    name: voting-deploy
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-voting-app
      name: voting-pod
  template:
    metadata:
      name: voting-pod
      labels:
        name: voting-pod
        app: demo-voting-app
    spec:
      containers:
        - name: voting-pod
          image: kodekloud/examplevotingapp_vote:v1
          ports:
            - containerPort: 80
