apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
  labels:
    name: db-deploy
    app: demo-voting-app
spec:
  selector:
    matchLabels:
      app: demo-voting-app
      name: db-pod
  template:
    metadata:
      name: db-pod
      labels:
        app: demo-voting-app
        name: db-pod
    spec:
      containers:
        - name: db-pod
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
