apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    app: demo-voting-app
    name: db-pod
spec:
  containers:
    - name: db-pod
      image: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
