apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment2
  labels:
    app: myapp-deployment2
spec:
  selector:
    matchLabels:
      app: myapp2
  replicas: 6
  template:
    metadata:
      name: nginx
      labels:
        app: myapp2
    spec:
      containers:
        - name: nginx
          image: nginx
