apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: demo-voting-app
    name: db-service
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: db-pod
    app: demo-voting-app
