apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: demo-voting-app
    name: result-service
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30005
  selector:
    name: result-pod
    app: demo-voting-app
