apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: new-replica-set
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 4
  template:
    metadata:
      name: busybox
      labels:
        app: myapp
    spec:
      containers:
        - name: busybox
          image: nginx
